version: '3.8'
services:
  checkouts:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8002:8000
    depends_on:
      - checkouts_db

  # admin_queue:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: 'php artisan queue:work'
  #   depends_on:
  #     - catalogs_db

  checkouts_db:
    image: mysql:5.7.22
    ulimits:
      nproc: 262144
      nofile:
        soft: 10000
        hard: 20000
    environment:
      MYSQL_DATABASE: checkouts
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33062:3306


